#Capstone Config
version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.7.3-stretch
  aws:
    docker:
      - image: amazon/aws-cli

jobs:
  linting:
    executor: python
    steps:
      - checkout
      - run:
          name: Make Lint 
          command: |
            sudo apt-get update
            sudo apt-get install python3-venv
            python3 -m venv virtualenv
            . virtualenv/bin/activate
            make install
            make lint
  build:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build, tag and push docker image to docker.io
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PWD}
            docker build -t 01141942205/devopsproject5:${CIRCLE_WORKFLOW_ID:0:7} .
            docker push 01141942205/devopsproject5:${CIRCLE_WORKFLOW_ID:0:7}
            docker tag 01141942205/devopsproject5:${CIRCLE_WORKFLOW_ID:0:7} 01141942205/devopsproject5:latest
            docker push 01141942205/devopsproject5:latest
  
  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          devopsproject5
        type: string
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: appdeployment.yml
          resource-name: deployment/devopsproject5

  test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          devopsproject5
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          name: Test cluster
          command: |
            kubectl get svc
            kubectl get nodes
            kubectl get deployment
                      
orbs:
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@0.11.2

workflows:
  deployment:
    jobs:
      - linting
